<?
$nazwa_sklepu = "Sklep internetowy MONIKA";
$telefon_sklepu = "(509) 240-859";
$email_sklepu = "jjprojekt@poczta.fm";
$adres_sklepu = "97-300 Piotrków Tryb., Al.3-go Maja 31";
$url_sklepu = "http://www.tbs.piotrkow.pl/sklep/";

$databasename = "sklep";
$databaseuser = "root";
$databasepasswd = "";

$orderrecipient = "jjprojekt@poczta.fm";
$ordersubject = "Zamówienie ze sklepu internetowego: MONIKA - 02-495 Warszawa, ul. Ku¼nicy Ko³³±tajowskiej 61";
$timezoneoffset = 26820;

// -----------------------------------
//  inne rzeczy konfiguracyjne sklepu
// -----------------------------------

// styl kolorów (nazwa pliku stylu kolorów z rozszerzeniem .css)
$styl_main="main5.css";
// czy oddzieliæ boki sklepu (³adniej wygl±da) i srodek (niekoniecznie)...
$oddziel_boki=1;
$oddziel_srodek=1;
// czy odstêp po belce - je¶li 0 to nie - inaczej - wielko¶æ odstêpu :-)
$odstep_po_belce=0;
// czy rozdzielaæ przerywan± lini± produkty (równie¿ promocje) od siebie
$linie_podzialu=0;

// czy pokazywaæ towary z ilo¶ci± <=0 (ignoruj±c ilo¶æ w bazie)?
$pokazuj_ujemne=1;
// czy pokazywaæ cene netto (1 tak, 0 nie) w sklepie (pokazuje w edycji zawsze)
$pokazuj_netto=0;
// czy pokazywaæ obrazek - ilo¶æ wybranych produktów
$pokazuj_ilosc=1;

// czy pod opisem umie¶ciæ tabelkê z kategoriami i z symbolem
$produkty_tabelka=1;
// czy pokazywaæ czê¶æ zawieraj±c± cennik
$pokaz_cennik=1;
// ilo¶æ wy¶wietlanych ostatnio dodanych
$ilosc_ostatnich=5;
// ilo¶æ wy¶wietlanych najczê¶ciej kupowanych
$ilosc_kupowanych=5;
// szeroko¶æi wysoko¶æ obrazka - miniaturki
$thumb_w=150;
$thumb_h=120;
// skala ilo¶ci produktów dla wy¶wietlania belki informuj±cej o ilo¶ci produktów
// wg tej skali procentowo zape³niana jest belka ilo¶ci produktu w bazie
$skala_ilosci=100;
// plik logo (dla zamówienia :-0)
$logo='images/logo.jpg';
// cennik - stopka reklamowa (np. NISKIE CENY, ZAPRASZAMY)
$logo_stopka="NISKIE CENY, ZAPRASZAMY";
?>
